Support Readonly Parameter Plugin
MCMicS/jenkins-control-plugin pull request #649
Opened 2024-12-16 16:21 UTC by nikrabaev

Adds support for `WReadonlyStringParameterDefinition` and `WReadonlyTextParameterDefinition`.
Link: [https://plugins.jenkins.io/readonly-parameters](https://plugins.jenkins.io/readonly-parameters)

2024-12-16 17:17 UTC, MCMicS requested changes

2024-12-16 17:17 UTC, MCMicS commented on src/main/java/org/codinjutsu/tools/jenkins/view/extension/JobParameterRenderers.java
> +    public static JobParameterComponent<String> createTextArea(JobParameter jobParameter, String defaultValue, boolean isReadonly = false) {
This will not work on Java with default method. please add a second method for readOnly

2024-12-16 17:17 UTC, MCMicS commented on src/main/java/org/codinjutsu/tools/jenkins/view/parameter/ReadonlyParameterRenderer.java
> +        return converter.getOrDefault(jobParameterType, JobParameterRenderers::createErrorLabel).apply(jobParameter, defaultValue, false);
Where you set a value to  `true`.
it looks the PR is not complete

2024-12-16 17:28 UTC, MCMicS commented
What you can withou need of additional method is maybe following

```
    public ReadonlyParameterRenderer() {
        converter.put(STRING, makeReadOnly(JobParameterRenderers::createTextField));
        converter.put(TEXT, makeReadOnly(JobParameterRenderers::createTextArea));
    }

    private BiFunction<JobParameter, String, JobParameterComponent<?>> makeReadOnly(
            BiFunction<JobParameter, String, JobParameterComponent<?>> textCreator) {
        return textCreator.andThen(this::makeReadOnly);
    }

    private <R> JobParameterComponent<R> makeReadOnly(JobParameterComponent<R> jobParameterComponent) {
        final JComponent viewElement = jobParameterComponent.getViewElement();
        if (viewElement instanceof JTextComponent textComponent) {
            textComponent.setEditable(false);
        }
        return jobParameterComponent;
    }
 ```

2024-12-16 17:41 UTC, MCMicS commented
Or simple let create label instead text fields. Because if they are are all read-only it is only text right?

2024-12-16 18:04 UTC, MCMicS commented
Ok
No problem. I can look at this zhr next days and maybe improve it to make the parameters make work.
But is it needed to have text fields or is a simple label enough to see the set value

2024-12-16 18:10 UTC, nikrabaev commented
@MCMicS I think it's better to keep it closer to the original Jenkins design, where it's just a non-editable input/textarea. I assume rendering strings as labels would not be too hard, but I'm not so sure about text areas since they may contain a lot of text.

2024-12-16 18:11 UTC, MCMicS commented
Ok
I do it the days and provide version for test ok?

2024-12-16 18:21 UTC, nikrabaev commented
@MCMicS Btw, I've just tested it locally and it worked like a charm.

2024-12-16 19:12 UTC, MCMicS commented
yes look ok
sample below:
![grafik](https://github.com/user-attachments/assets/1f8a7461-2069-43a2-a8e0-19470757785c)

2024-12-16 19:16 UTC, merged

2024-12-16 19:19 UTC, MCMicS commented
Test plugin here: [jenkins-control-plugin-0.13.21-eap-2023.2-signed.zip](https://github.com/user-attachments/files/18156096/jenkins-control-plugin-0.13.21-eap-2023.2-signed.zip)

2024-12-16 19:20 UTC, MCMicS commented
Thanks for commiting

2025-09-03 20:44 UTC, MCMicS commented
released with [0.13.21](https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/stable/849149)